import { FoundationMatch } from '@/types';

export const FOUNDATION_DATABASE: Omit<FoundationMatch, 'matchScore'>[] = [
  // ===== FAIR =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '100', shadeCode: '100', hexColor: '#EFCFA4', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '110', shadeCode: '110', hexColor: '#D1BBA9', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Porcelain', shadeCode: '112', hexColor: '#EFCFA4', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Fair Ivory', shadeCode: '118', hexColor: '#D1BBA9', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC12', shadeCode: 'NC12', hexColor: '#EFCFA4', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW13', shadeCode: 'NW13', hexColor: '#D1BBA9', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W2', shadeCode: 'W2', hexColor: '#EFCFA4', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N1', shadeCode: 'N1', hexColor: '#D1BBA9', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Mont Blanc', shadeCode: '1', hexColor: '#EFCFA4', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Siberia', shadeCode: '2', hexColor: '#D1BBA9', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '1N1', shadeCode: '1N1', hexColor: '#EFCFA4', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '1W0', shadeCode: '1W0', hexColor: '#D1BBA9', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Truly Topaz', shadeCode: '1', hexColor: '#EFCFA4', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Beautiful Bronze Light', shadeCode: '2', hexColor: '#D1BBA9', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Fair', shadeCode: '1', hexColor: '#EFCFA4', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Warm Silk', shadeCode: '2', hexColor: '#D1BBA9', price: '$6.99', url: '#' },

  // ===== LIGHT =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '150', shadeCode: '150', hexColor: '#CEB28B', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '160', shadeCode: '160', hexColor: '#B5A294', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Warm Ivory', shadeCode: '125', hexColor: '#CEB28B', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Classic Ivory', shadeCode: '120', hexColor: '#B5A294', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC20', shadeCode: 'NC20', hexColor: '#CEB28B', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW20', shadeCode: 'NW20', hexColor: '#B5A294', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W3', shadeCode: 'W3', hexColor: '#CEB28B', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N2', shadeCode: 'N2', hexColor: '#B5A294', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Gobi', shadeCode: '3', hexColor: '#CEB28B', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Punjab', shadeCode: '4', hexColor: '#B5A294', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '2N1', shadeCode: '2N1', hexColor: '#CEB28B', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '2W0', shadeCode: '2W0', hexColor: '#B5A294', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Carob', shadeCode: '3', hexColor: '#CEB28B', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Toffee', shadeCode: '4', hexColor: '#B5A294', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'True Beige', shadeCode: '3', hexColor: '#CEB28B', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Sandy Beige', shadeCode: '4', hexColor: '#B5A294', price: '$6.99', url: '#' },

  // ===== LIGHT-MEDIUM =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '190', shadeCode: '190', hexColor: '#B49C77', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '200', shadeCode: '200', hexColor: '#9C8B80', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Nude Beige', shadeCode: '128', hexColor: '#B49C77', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Buff Beige', shadeCode: '122', hexColor: '#9C8B80', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC25', shadeCode: 'NC25', hexColor: '#B49C77', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW25', shadeCode: 'NW25', hexColor: '#9C8B80', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N3', shadeCode: 'N3', hexColor: '#B49C77', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W4', shadeCode: 'W4', hexColor: '#9C8B80', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Deauville', shadeCode: '5', hexColor: '#B49C77', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Tahoe', shadeCode: '6', hexColor: '#9C8B80', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '3N1', shadeCode: '3N1', hexColor: '#B49C77', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '3W1', shadeCode: '3W1', hexColor: '#9C8B80', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Beautiful Bronze', shadeCode: '5', hexColor: '#B49C77', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Heavenly Honey', shadeCode: '6', hexColor: '#9C8B80', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Warm Honey', shadeCode: '5', hexColor: '#B49C77', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Nutmeg Light', shadeCode: '6', hexColor: '#9C8B80', price: '$6.99', url: '#' },

  // ===== MEDIUM =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '240', shadeCode: '240', hexColor: '#9B8564', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '260', shadeCode: '260', hexColor: '#82756D', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Sun Beige', shadeCode: '310', hexColor: '#9B8564', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Golden Beige', shadeCode: '220', hexColor: '#82756D', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC35', shadeCode: 'NC35', hexColor: '#9B8564', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW35', shadeCode: 'NW35', hexColor: '#82756D', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W6', shadeCode: 'W6', hexColor: '#9B8564', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N4', shadeCode: 'N4', hexColor: '#82756D', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Fiji', shadeCode: '7', hexColor: '#9B8564', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Barcelona', shadeCode: '8', hexColor: '#82756D', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '4N1', shadeCode: '4N1', hexColor: '#9B8564', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '4W1', shadeCode: '4W1', hexColor: '#82756D', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Amber Glow', shadeCode: '7', hexColor: '#9B8564', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Bronze Glow', shadeCode: '8', hexColor: '#82756D', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Golden Sand', shadeCode: '7', hexColor: '#9B8564', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Bronze', shadeCode: '8', hexColor: '#82756D', price: '$6.99', url: '#' },

  // ===== MEDIUM-DEEP =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '290', shadeCode: '290', hexColor: '#816F50', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '310', shadeCode: '310', hexColor: '#695E59', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Caramel', shadeCode: '330', hexColor: '#816F50', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Honey', shadeCode: '235', hexColor: '#695E59', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC42', shadeCode: 'NC42', hexColor: '#816F50', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW42', shadeCode: 'NW42', hexColor: '#695E59', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N6', shadeCode: 'N6', hexColor: '#816F50', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W7', shadeCode: 'W7', hexColor: '#695E59', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'New Orleans', shadeCode: '9', hexColor: '#816F50', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Cadiz', shadeCode: '10', hexColor: '#695E59', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '5N1', shadeCode: '5N1', hexColor: '#816F50', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '5W1', shadeCode: '5W1', hexColor: '#695E59', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Truly Topaz Deep', shadeCode: '9', hexColor: '#816F50', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Rich Caramel', shadeCode: '10', hexColor: '#695E59', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Brown Sugar', shadeCode: '9', hexColor: '#816F50', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Cinnamon', shadeCode: '10', hexColor: '#695E59', price: '$6.99', url: '#' },

  // ===== DEEP =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '370', shadeCode: '370', hexColor: '#68583D', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '390', shadeCode: '390', hexColor: '#4F4846', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Coconut', shadeCode: '356', hexColor: '#68583D', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Mocha', shadeCode: '315', hexColor: '#4F4846', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC50', shadeCode: 'NC50', hexColor: '#68583D', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW47', shadeCode: 'NW47', hexColor: '#4F4846', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W8', shadeCode: 'W8', hexColor: '#68583D', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N7', shadeCode: 'N7', hexColor: '#4F4846', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Macao', shadeCode: '11', hexColor: '#68583D', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Benares', shadeCode: '12', hexColor: '#4F4846', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '6N1', shadeCode: '6N1', hexColor: '#68583D', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '6W1', shadeCode: '6W1', hexColor: '#4F4846', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Espresso', shadeCode: '11', hexColor: '#68583D', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Chestnut', shadeCode: '12', hexColor: '#4F4846', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Chocolate', shadeCode: '11', hexColor: '#68583D', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Java', shadeCode: '12', hexColor: '#4F4846', price: '$6.99', url: '#' },

  // ===== RICH =====
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '440', shadeCode: '440', hexColor: '#51442B', price: '$40', url: '#' },
  { brand: 'Fenty Beauty', productName: "Pro Filt'r Soft Matte", shadeName: '460', shadeCode: '460', hexColor: '#2E2B2D', price: '$40', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Java', shadeCode: '360', hexColor: '#51442B', price: '$9.49', url: '#' },
  { brand: 'Maybelline', productName: "Fit Me Matte + Poreless", shadeName: 'Espresso', shadeCode: '370', hexColor: '#2E2B2D', price: '$9.49', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NC58', shadeCode: 'NC58', hexColor: '#51442B', price: '$40', url: '#' },
  { brand: 'MAC', productName: "Studio Fix Fluid", shadeName: 'NW58', shadeCode: 'NW58', hexColor: '#2E2B2D', price: '$40', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'N8', shadeCode: 'N8', hexColor: '#51442B', price: '$10.99', url: '#' },
  { brand: "L'Oreal", productName: "True Match", shadeName: 'W10', shadeCode: 'W10', hexColor: '#2E2B2D', price: '$10.99', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Trinidad', shadeCode: '13', hexColor: '#51442B', price: '$49', url: '#' },
  { brand: 'NARS', productName: "Natural Radiant Longwear", shadeName: 'Kalahari', shadeCode: '14', hexColor: '#2E2B2D', price: '$49', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '7N1', shadeCode: '7N1', hexColor: '#51442B', price: '$46', url: '#' },
  { brand: 'Estee Lauder', productName: "Double Wear Stay-in-Place", shadeName: '7W1', shadeCode: '7W1', hexColor: '#2E2B2D', price: '$46', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Nutmeg', shadeCode: '13', hexColor: '#51442B', price: '$9.99', url: '#' },
  { brand: 'Black Opal', productName: "True Color Skin Perfecting Foundation", shadeName: 'Deep Umber', shadeCode: '14', hexColor: '#2E2B2D', price: '$9.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Espresso Bean', shadeCode: '13', hexColor: '#51442B', price: '$6.99', url: '#' },
  { brand: 'Black Radiance', productName: "True Complexion Foundation", shadeName: 'Dark Cocoa', shadeCode: '14', hexColor: '#2E2B2D', price: '$6.99', url: '#' },

];
